# Generated by Django 5.0.4 on 2024-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=200, null=True)),
                ("response", models.CharField(blank=True, max_length=600, null=True)),
                (
                    "chat_context",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.UUIDField()),
                ("userText", models.CharField(blank=True, max_length=600, null=True)),
                ("VTAText", models.CharField(blank=True, max_length=200, null=True)),
                ("likeStatus", models.BooleanField()),
            ],
        ),
    ]
