# Generated by Django 5.0.4 on 2024-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="VTAText",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="userText",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
