# Generated by Django 5.0.4 on 2024-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_rating_vtatext_alter_rating_usertext"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikeResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.UUIDField()),
                ("userText", models.CharField(blank=True, max_length=200, null=True)),
                ("VTAText", models.CharField(blank=True, max_length=1000, null=True)),
                ("likeStatus", models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Rating",
            new_name="DislikeResponse",
        ),
    ]
